name: Trivy Security Scan

on:
  push:
    branches:
      - cmd
  pull_request:
    branches:
      - cmd

jobs:
  trivy_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build the Docker image
      run: docker build -t my-app .

    - name: Install Trivy
      run: |
        echo "Installing Trivy..."
        sudo apt-get update
        wget -qO- https://github.com/aquasecurity/trivy/releases/download/v0.45.0/trivy_0.45.0_Linux-64bit.tar.gz | tar xzv
        sudo mv trivy /usr/local/bin/
        trivy --version

    - name: Run Trivy scan
      run: |
        echo "Running Trivy scan..."
        trivy image --severity CRITICAL --ignore-unfixed --exit-code 1 --format table --output trivy_report.txt my-app

    - name: Upload Trivy report
      uses: actions/upload-artifact@v3
      with:
        name: trivy-report
        path: trivy_report.txt

    - name: Show scan report
      if: failure()
      run: cat trivy_report.txt

    - name: Set build status based on Trivy scan
      if: failure()
      run: echo "Vulnerabilities found, failing the build."
